[tool.poetry]
name = "speccify"
version = "0.1.0"
description = ""
authors = ["Lyst Ltd. <devs@lyst.com>"]

[tool.poetry.dependencies]
python = "^3.7"
djangorestframework = "*"
djangorestframework-dataclasses = "*"
drf-spectacular = "*"
typing-extensions = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-django = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
profile = "black"
